# Generated by Haxe 4.3.7
# coding: utf-8
import sys

import random as python_lib_Random
from tlesenpy.tlesen import Taibolesen as tlesenhx_Taibolesen
import pygame as tlesenhx_KeyCodes
import pygame.draw as tlesenhx_Draw


class Raindrop:
    __slots__ = ("x", "y", "speed", "length")

    def __init__(self,screenW,screenH):
        self.length = None
        self.speed = None
        self.y = None
        self.x = None
        self.respawn(screenW,screenH)
        self.y = (python_lib_Random.random() * screenH)

    def respawn(self,screenW,screenH):
        self.x = (python_lib_Random.random() * screenW)
        self.y = -20
        self.speed = (10 + ((python_lib_Random.random() * 10)))
        x = (python_lib_Random.random() * 15)
        tmp = None
        try:
            tmp = int(x)
        except BaseException as _g:
            tmp = None
        self.length = (5 + tmp)

    def update(self,screenW,screenH):
        _hx_local_0 = self
        _hx_local_1 = _hx_local_0.y
        _hx_local_0.y = (_hx_local_1 + self.speed)
        _hx_local_0.y
        if (self.y > screenH):
            self.respawn(screenW,screenH)



class Main:
    __slots__ = ()

    @staticmethod
    def main():
        engine = tlesenhx_Tlesen.init(800,600)
        playerImg = engine.load_image("dude.png")
        px = 100
        py = 400
        raindrops = []
        _g = 0
        while (_g < 150):
            i = _g
            _g = (_g + 1)
            x = Raindrop(800,600)
            raindrops.append(x)
        def _hx_local_4():
            nonlocal py
            nonlocal px
            nonlocal px
            keys = engine.get_keys()
            if keys[tlesenhx_KeyCodes.K_LEFT]:
                px = (px - 7)
            if keys[tlesenhx_KeyCodes.K_RIGHT]:
                px = (px + 7)
            _g = 0
            while (_g < len(raindrops)):
                drop = (raindrops[_g] if _g >= 0 and _g < len(raindrops) else None)
                _g = (_g + 1)
                drop.update(engine.width,engine.height)
            if (py > ((engine.height - 100))):
                py = (engine.height - 100)
            engine.clear_layered()
            engine.draw_image(playerImg,px,py)
            _g = 0
            while (_g < len(raindrops)):
                drop = (raindrops[_g] if _g >= 0 and _g < len(raindrops) else None)
                _g = (_g + 1)
                engine1 = engine.screen
                x = drop.x
                update = None
                try:
                    update = int(x)
                except BaseException as _g1:
                    update = None
                x1 = drop.y
                update1 = None
                try:
                    update1 = int(x1)
                except BaseException as _g2:
                    update1 = None
                tlesenhx_Draw.rect(engine1,[180, 180, 200],[update, update1, 2, drop.length])
        update = _hx_local_4
        engine.run(update)


class haxe_iterators_ArrayIterator:
    __slots__ = ("array", "current")

    def __init__(self,array):
        self.current = 0
        self.array = array

    def hasNext(self):
        return (self.current < len(self.array))

    def next(self):
        def _hx_local_3():
            def _hx_local_2():
                _hx_local_0 = self
                _hx_local_1 = _hx_local_0.current
                _hx_local_0.current = (_hx_local_1 + 1)
                return _hx_local_1
            return python_internal_ArrayImpl._get(self.array, _hx_local_2())
        return _hx_local_3()



class python_internal_ArrayImpl:
    __slots__ = ()

    @staticmethod
    def _get(x,idx):
        if ((idx > -1) and ((idx < len(x)))):
            return x[idx]
        else:
            return None


class python_internal_MethodClosure:
    __slots__ = ("obj", "func")

    def __init__(self,obj,func):
        self.obj = obj
        self.func = func

    def __call__(self,*args):
        return self.func(self.obj,*args)



class tlesenhx_Tlesen:
    __slots__ = ()

    @staticmethod
    def init(w,h):
        return tlesenhx_Taibolesen(w,h)



Main.main()
